### PR TITLE
OFFAPPS-660 add new translations

### PR DESCRIPTION
**Pull request by sandlerr**
:v:

/cc @zendesk/vegemite

### Description

update translations

### References
* JIRA: https://zendesk.atlassian.net/browse/OFFAPPS-660

### Risks
* None

### CODE REVIEW

**Comment by sandlerr** [comment]
@ydrain there was no Czech translation update as you mentioned on the [JIRA story](https://zendesk.atlassian.net/browse/OFFAPPS-660), which key is it under?

**Comment by adammw** [comment]
:+1:

**Comment by svizzari** [comment]
:+1:

**Comment by ocke** [comment]
:fist:

**Comment by ydrain** [comment]
Olaf added these strings back in September:
https://github.com/zendesk/attachment_viewer_app/commit/da7c5f21

We still don't see Czech on Production. (https://www.evernote.com/l/APT9zUKcnFBPUqTgjm8-u0sZfs4XI71Ihkg) The latest built on Production includes the latest translations?

**Comment by ydrain** [comment]
:+1:

**Comment by sandlerr** [comment]
@ydrain we never deployed it to production, I'll do that today.
cc @ocke

**Comment by ydrain** [comment]
Hmmm...any other apps are outdated?

**Pull request merged**
