### PR TITLE
[ZD#1030467] Allow validation of different case file extensions...

### PR DESCRIPTION
**Pull request by jbantz**
....

Converts filename to lowercase to validate against existing permitted
file extensions.

@maximeprades

### CODE REVIEW

**Comment by maximeprades** [comment]
cc @zendesk/quokka

**Comment by adammw** [comment]
I think the plan looks like there should have been a case insensitive regex, but it wasn't implemented that way. Thanks for the fix, :+1:

**Comment by jbdietrich** [comment]
I'm not a quokka, but it seems pretty straightforward to me. :+1:

**Comment by adammw** [comment]
@jbantz just a heads up we don't have auto-deployment of apps (yet). @zendesk/quokka can someone bump the version and tag and updating staging so we can QA?

**Comment by princemaple** [comment]
Sure

**Pull request merged**
